version: "3.9"

services:
  multifbot:
    image: ghcr.io/missemily22/multifunctionbot:lite
    container_name: multifbot
    environment:
      - CONFIG_FILE_URL=${CONFIG_FILE_URL}
    ports:
      - "8080:8080"
    restart: unless-stopped